"""AlphaFlow FastAPI backend — REST API for the microstructure alpha engine.

Exposes 12+ endpoints across four groups:
    /api/pipeline/*   : Trigger pipeline runs, poll status, retrieve run history
    /api/signals/*    : Latest per-ticker signal cards, bulk aggregates
    /api/intraday/*   : hourly walk-forward results, SHAP importance
    /api/data/*       : Raw OHLCV CSV download, ticker management, SSE stream

Server:  uvicorn backend.main:app --reload --port 8002
Docs:    http://localhost:8002/docs  (Swagger UI auto-generated by FastAPI)
"""
